<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipalitiesTableSeeder extends Seeder
{
    public function run()
    {
        $municipalities = [
            // Amazonas
            ['state_id' => 1, 'name' => 'Alto Orinoco', 'code' => 'AMA001'],
            ['state_id' => 1, 'name' => 'Atabapo', 'code' => 'AMA002'],
            ['state_id' => 1, 'name' => 'Atures', 'code' => 'AMA003'],
            ['state_id' => 1, 'name' => 'Autana', 'code' => 'AMA004'],
            ['state_id' => 1, 'name' => 'Manapiare', 'code' => 'AMA005'],
            ['state_id' => 1, 'name' => 'Maroa', 'code' => 'AMA006'],
            ['state_id' => 1, 'name' => 'Río Negro', 'code' => 'AMA007'],

            // Anzoátegui
            ['state_id' => 2, 'name' => 'Anaco', 'code' => 'ANZ001'],
            ['state_id' => 2, 'name' => 'Aragua', 'code' => 'ANZ002'],
            ['state_id' => 2, 'name' => 'Bolívar', 'code' => 'ANZ003'],
            ['state_id' => 2, 'name' => 'Bruzual', 'code' => 'ANZ004'],
            ['state_id' => 2, 'name' => 'Cajigal', 'code' => 'ANZ005'],
            ['state_id' => 2, 'name' => 'Carvajal', 'code' => 'ANZ006'],
            ['state_id' => 2, 'name' => 'Diego Bautista Urbaneja', 'code' => 'ANZ007'],
            ['state_id' => 2, 'name' => 'Freites', 'code' => 'ANZ008'],
            ['state_id' => 2, 'name' => 'Guanipa', 'code' => 'ANZ009'],
            ['state_id' => 2, 'name' => 'Guanta', 'code' => 'ANZ010'],
            ['state_id' => 2, 'name' => 'Independencia', 'code' => 'ANZ011'],
            ['state_id' => 2, 'name' => 'Libertad', 'code' => 'ANZ012'],
            ['state_id' => 2, 'name' => 'McGregor', 'code' => 'ANZ013'],
            ['state_id' => 2, 'name' => 'Miranda', 'code' => 'ANZ014'],
            ['state_id' => 2, 'name' => 'Monagas', 'code' => 'ANZ015'],
            ['state_id' => 2, 'name' => 'Peñalver', 'code' => 'ANZ016'],
            ['state_id' => 2, 'name' => 'Píritu', 'code' => 'ANZ017'],
            ['state_id' => 2, 'name' => 'San Juan de Capistrano', 'code' => 'ANZ018'],
            ['state_id' => 2, 'name' => 'Santa Ana', 'code' => 'ANZ019'],
            ['state_id' => 2, 'name' => 'Simón Rodríguez', 'code' => 'ANZ020'],
            ['state_id' => 2, 'name' => 'Sotillo', 'code' => 'ANZ021'],

            // Apure
            ['state_id' => 3, 'name' => 'Achaguas', 'code' => 'APU001'],
            ['state_id' => 3, 'name' => 'Biruaca', 'code' => 'APU002'],
            ['state_id' => 3, 'name' => 'Muñóz', 'code' => 'APU003'],
            ['state_id' => 3, 'name' => 'Páez', 'code' => 'APU004'],
            ['state_id' => 3, 'name' => 'Pedro Camejo', 'code' => 'APU005'],
            ['state_id' => 3, 'name' => 'Rómulo Gallegos', 'code' => 'APU006'],
            ['state_id' => 3, 'name' => 'San Fernando', 'code' => 'APU007'],

            // Aragua
            ['state_id' => 4, 'name' => 'Bolívar', 'code' => 'ARA001'],
            ['state_id' => 4, 'name' => 'Camatagua', 'code' => 'ARA002'],
            ['state_id' => 4, 'name' => 'Francisco Linares Alcántara', 'code' => 'ARA003'],
            ['state_id' => 4, 'name' => 'Girardot', 'code' => 'ARA004'],
            ['state_id' => 4, 'name' => 'José Ángel Lamas', 'code' => 'ARA005'],
            ['state_id' => 4, 'name' => 'José Félix Ribas', 'code' => 'ARA006'],
            ['state_id' => 4, 'name' => 'José Rafael Revenga', 'code' => 'ARA007'],
            ['state_id' => 4, 'name' => 'Libertador', 'code' => 'ARA008'],
            ['state_id' => 4, 'name' => 'Mario Briceño Iragorry', 'code' => 'ARA009'],
            ['state_id' => 4, 'name' => 'Ocumare de la Costa de Oro', 'code' => 'ARA010'],
            ['state_id' => 4, 'name' => 'San Casimiro', 'code' => 'ARA011'],
            ['state_id' => 4, 'name' => 'San Sebastián', 'code' => 'ARA012'],
            ['state_id' => 4, 'name' => 'Santiago Mariño', 'code' => 'ARA013'],
            ['state_id' => 4, 'name' => 'Santos Michelena', 'code' => 'ARA014'],
            ['state_id' => 4, 'name' => 'Sucre', 'code' => 'ARA015'],
            ['state_id' => 4, 'name' => 'Tovar', 'code' => 'ARA016'],
            ['state_id' => 4, 'name' => 'Urdaneta', 'code' => 'ARA017'],
            ['state_id' => 4, 'name' => 'Zamora', 'code' => 'ARA018'],

            // Barinas
            ['state_id' => 5, 'name' => 'Alberto Arvelo Torrealba', 'code' => 'BAR001'],
            ['state_id' => 5, 'name' => 'Andrés Eloy Blanco', 'code' => 'BAR002'],
            ['state_id' => 5, 'name' => 'Antonio José de Sucre', 'code' => 'BAR003'],
            ['state_id' => 5, 'name' => 'Arismendi', 'code' => 'BAR004'],
            ['state_id' => 5, 'name' => 'Barinas', 'code' => 'BAR005'],
            ['state_id' => 5, 'name' => 'Bolívar', 'code' => 'BAR006'],
            ['state_id' => 5, 'name' => 'Cruz Paredes', 'code' => 'BAR007'],
            ['state_id' => 5, 'name' => 'Ezequiel Zamora', 'code' => 'BAR008'],
            ['state_id' => 5, 'name' => 'Obispos', 'code' => 'BAR009'],
            ['state_id' => 5, 'name' => 'Pedraza', 'code' => 'BAR010'],
            ['state_id' => 5, 'name' => 'Rojas', 'code' => 'BAR011'],
            ['state_id' => 5, 'name' => 'Sosa', 'code' => 'BAR012'],

            // Bolívar
            ['state_id' => 6, 'name' => 'Caroní', 'code' => 'BOL001'],
            ['state_id' => 6, 'name' => 'Cedeño', 'code' => 'BOL002'],
            ['state_id' => 6, 'name' => 'El Callao', 'code' => 'BOL003'],
            ['state_id' => 6, 'name' => 'Gran Sabana', 'code' => 'BOL004'],
            ['state_id' => 6, 'name' => 'Heres', 'code' => 'BOL005'],
            ['state_id' => 6, 'name' => 'Piar', 'code' => 'BOL006'],
            ['state_id' => 6, 'name' => 'Angostura (Raúl Leoni)', 'code' => 'BOL007'],
            ['state_id' => 6, 'name' => 'Roscio', 'code' => 'BOL008'],
            ['state_id' => 6, 'name' => 'Sifontes', 'code' => 'BOL009'],
            ['state_id' => 6, 'name' => 'Sucre', 'code' => 'BOL010'],
            ['state_id' => 6, 'name' => 'Padre Pedro Chien', 'code' => 'BOL011'],

            // Carabobo
            ['state_id' => 7, 'name' => 'Bejuma', 'code' => 'CAR001'],
            ['state_id' => 7, 'name' => 'Carlos Arvelo', 'code' => 'CAR002'],
            ['state_id' => 7, 'name' => 'Diego Ibarra', 'code' => 'CAR003'],
            ['state_id' => 7, 'name' => 'Guacara', 'code' => 'CAR004'],
            ['state_id' => 7, 'name' => 'Juan José Mora', 'code' => 'CAR005'],
            ['state_id' => 7, 'name' => 'Libertador', 'code' => 'CAR006'],
            ['state_id' => 7, 'name' => 'Los Guayos', 'code' => 'CAR007'],
            ['state_id' => 7, 'name' => 'Miranda', 'code' => 'CAR008'],
            ['state_id' => 7, 'name' => 'Montalbán', 'code' => 'CAR009'],
            ['state_id' => 7, 'name' => 'Naguanagua', 'code' => 'CAR010'],
            ['state_id' => 7, 'name' => 'Puerto Cabello', 'code' => 'CAR011'],
            ['state_id' => 7, 'name' => 'San Diego', 'code' => 'CAR012'],
            ['state_id' => 7, 'name' => 'San Joaquín', 'code' => 'CAR013'],
            ['state_id' => 7, 'name' => 'Valencia', 'code' => 'CAR014'],

            // Cojedes
            ['state_id' => 8, 'name' => 'Anzoátegui', 'code' => 'COJ001'],
            ['state_id' => 8, 'name' => 'Tinaquillo', 'code' => 'COJ002'],
            ['state_id' => 8, 'name' => 'Girardot', 'code' => 'COJ003'],
            ['state_id' => 8, 'name' => 'Lima Blanco', 'code' => 'COJ004'],
            ['state_id' => 8, 'name' => 'Pao de San Juan Bautista', 'code' => 'COJ005'],
            ['state_id' => 8, 'name' => 'Ricaurte', 'code' => 'COJ006'],
            ['state_id' => 8, 'name' => 'Rómulo Gallegos', 'code' => 'COJ007'],
            ['state_id' => 8, 'name' => 'Ezequiel Zamora', 'code' => 'COJ008'],
            ['state_id' => 8, 'name' => 'Tinaco', 'code' => 'COJ009'],

            // Delta Amacuro
            ['state_id' => 9, 'name' => 'Antonio Díaz', 'code' => 'DAM001'],
            ['state_id' => 9, 'name' => 'Casacoima', 'code' => 'DAM002'],
            ['state_id' => 9, 'name' => 'Pedernales', 'code' => 'DAM003'],
            ['state_id' => 9, 'name' => 'Tucupita', 'code' => 'DAM004'],

            // Falcón
            ['state_id' => 10, 'name' => 'Acosta', 'code' => 'FAL001'],
            ['state_id' => 10, 'name' => 'Bolívar', 'code' => 'FAL002'],
            ['state_id' => 10, 'name' => 'Buchivacoa', 'code' => 'FAL003'],
            ['state_id' => 10, 'name' => 'Cacique Manaure', 'code' => 'FAL004'],
            ['state_id' => 10, 'name' => 'Carirubana', 'code' => 'FAL005'],
            ['state_id' => 10, 'name' => 'Colina', 'code' => 'FAL006'],
            ['state_id' => 10, 'name' => 'Dabajuro', 'code' => 'FAL007'],
            ['state_id' => 10, 'name' => 'Democracia', 'code' => 'FAL008'],
            ['state_id' => 10, 'name' => 'Falcón', 'code' => 'FAL009'],
            ['state_id' => 10, 'name' => 'Federación', 'code' => 'FAL010'],
            ['state_id' => 10, 'name' => 'Jacura', 'code' => 'FAL011'],
            ['state_id' => 10, 'name' => 'Los Taques', 'code' => 'FAL012'],
            ['state_id' => 10, 'name' => 'Mauroa', 'code' => 'FAL013'],
            ['state_id' => 10, 'name' => 'Miranda', 'code' => 'FAL014'],
            ['state_id' => 10, 'name' => 'Monseñor Iturriza', 'code' => 'FAL015'],
            ['state_id' => 10, 'name' => 'Palmasola', 'code' => 'FAL016'],
            ['state_id' => 10, 'name' => 'Petit', 'code' => 'FAL017'],
            ['state_id' => 10, 'name' => 'Píritu', 'code' => 'FAL018'],
            ['state_id' => 10, 'name' => 'San Francisco', 'code' => 'FAL019'],
            ['state_id' => 10, 'name' => 'Sucre', 'code' => 'FAL020'],
            ['state_id' => 10, 'name' => 'Tocópero', 'code' => 'FAL021'],
            ['state_id' => 10, 'name' => 'Unión', 'code' => 'FAL022'],
            ['state_id' => 10, 'name' => 'Urumaco', 'code' => 'FAL023'],
            ['state_id' => 10, 'name' => 'Zamora', 'code' => 'FAL024'],

            // Guárico
            ['state_id' => 11, 'name' => 'Camaguán', 'code' => 'GUA001'],
            ['state_id' => 11, 'name' => 'Chaguaramas', 'code' => 'GUA002'],
            ['state_id' => 11, 'name' => 'El Socorro', 'code' => 'GUA003'],
            ['state_id' => 11, 'name' => 'Francisco de Miranda', 'code' => 'GUA004'],
            ['state_id' => 11, 'name' => 'José Félix Ribas', 'code' => 'GUA005'],
            ['state_id' => 11, 'name' => 'José Tadeo Monagas', 'code' => 'GUA006'],
            ['state_id' => 11, 'name' => 'Juan Germán Roscio', 'code' => 'GUA007'],
            ['state_id' => 11, 'name' => 'Julián Mellado', 'code' => 'GUA008'],
            ['state_id' => 11, 'name' => 'Las Mercedes', 'code' => 'GUA009'],
            ['state_id' => 11, 'name' => 'Leonardo Infante', 'code' => 'GUA010'],
            ['state_id' => 11, 'name' => 'Pedro Zaraza', 'code' => 'GUA011'],
            ['state_id' => 11, 'name' => 'Ortíz', 'code' => 'GUA012'],
            ['state_id' => 11, 'name' => 'San Gerónimo de Guayabal', 'code' => 'GUA013'],
            ['state_id' => 11, 'name' => 'San José de Guaribe', 'code' => 'GUA014'],
            ['state_id' => 11, 'name' => 'Santa María de Ipire', 'code' => 'GUA015'],

            // Lara
            ['state_id' => 12, 'name' => 'Andrés Eloy Blanco', 'code' => 'LAR001'],
            ['state_id' => 12, 'name' => 'Crespo', 'code' => 'LAR002'],
            ['state_id' => 12, 'name' => 'Iribarren', 'code' => 'LAR003'],
            ['state_id' => 12, 'name' => 'Jiménez', 'code' => 'LAR004'],
            ['state_id' => 12, 'name' => 'Morán', 'code' => 'LAR005'],
            ['state_id' => 12, 'name' => 'Palavecino', 'code' => 'LAR006'],
            ['state_id' => 12, 'name' => 'Simón Planas', 'code' => 'LAR007'],
            ['state_id' => 12, 'name' => 'Torres', 'code' => 'LAR008'],
            ['state_id' => 12, 'name' => 'Urdaneta', 'code' => 'LAR009'],

            // Mérida
            ['state_id' => 13, 'name' => 'Alberto Adriani', 'code' => 'MER001'],
            ['state_id' => 13, 'name' => 'Andrés Bello', 'code' => 'MER002'],
            ['state_id' => 13, 'name' => 'Antonio Pinto Salinas', 'code' => 'MER003'],
            ['state_id' => 13, 'name' => 'Aricagua', 'code' => 'MER004'],
            ['state_id' => 13, 'name' => 'Arzobispo Chacón', 'code' => 'MER005'],
            ['state_id' => 13, 'name' => 'Campo Elías', 'code' => 'MER006'],
            ['state_id' => 13, 'name' => 'Caracciolo Parra Olmedo', 'code' => 'MER007'],
            ['state_id' => 13, 'name' => 'Cardenal Quintero', 'code' => 'MER008'],
            ['state_id' => 13, 'name' => 'Guaraque', 'code' => 'MER009'],
            ['state_id' => 13, 'name' => 'Julio César Salas', 'code' => 'MER010'],
            ['state_id' => 13, 'name' => 'Justo Briceño', 'code' => 'MER011'],
            ['state_id' => 13, 'name' => 'Libertador', 'code' => 'MER012'],
            ['state_id' => 13, 'name' => 'Miranda', 'code' => 'MER013'],
            ['state_id' => 13, 'name' => 'Obispo Ramos de Lora', 'code' => 'MER014'],
            ['state_id' => 13, 'name' => 'Padre Noguera', 'code' => 'MER015'],
            ['state_id' => 13, 'name' => 'Pueblo Llano', 'code' => 'MER016'],
            ['state_id' => 13, 'name' => 'Rangel', 'code' => 'MER017'],
            ['state_id' => 13, 'name' => 'Rivas Dávila', 'code' => 'MER018'],
            ['state_id' => 13, 'name' => 'Santos Marquina', 'code' => 'MER019'],
            ['state_id' => 13, 'name' => 'Sucre', 'code' => 'MER020'],
            ['state_id' => 13, 'name' => 'Tovar', 'code' => 'MER021'],
            ['state_id' => 13, 'name' => 'Tulio Febres Cordero', 'code' => 'MER022'],
            ['state_id' => 13, 'name' => 'Zea', 'code' => 'MER023'],

            // Miranda
            ['state_id' => 14, 'name' => 'Acevedo', 'code' => 'MIR001'],
            ['state_id' => 14, 'name' => 'Andrés Bello', 'code' => 'MIR002'],
            ['state_id' => 14, 'name' => 'Baruta', 'code' => 'MIR003'],
            ['state_id' => 14, 'name' => 'Brión', 'code' => 'MIR004'],
            ['state_id' => 14, 'name' => 'Buroz', 'code' => 'MIR005'],
            ['state_id' => 14, 'name' => 'Carrizal', 'code' => 'MIR006'],
            ['state_id' => 14, 'name' => 'Chacao', 'code' => 'MIR007'],
            ['state_id' => 14, 'name' => 'Cristóbal Rojas', 'code' => 'MIR008'],
            ['state_id' => 14, 'name' => 'El Hatillo', 'code' => 'MIR009'],
            ['state_id' => 14, 'name' => 'Guaicaipuro', 'code' => 'MIR010'],
            ['state_id' => 14, 'name' => 'Independencia', 'code' => 'MIR011'],
            ['state_id' => 14, 'name' => 'Lander', 'code' => 'MIR012'],
            ['state_id' => 14, 'name' => 'Los Salias', 'code' => 'MIR013'],
            ['state_id' => 14, 'name' => 'Páez', 'code' => 'MIR014'],
            ['state_id' => 14, 'name' => 'Paz Castillo', 'code' => 'MIR015'],
            ['state_id' => 14, 'name' => 'Pedro Gual', 'code' => 'MIR016'],
            ['state_id' => 14, 'name' => 'Plaza', 'code' => 'MIR017'],
            ['state_id' => 14, 'name' => 'Simón Bolívar', 'code' => 'MIR018'],
            ['state_id' => 14, 'name' => 'Sucre', 'code' => 'MIR019'],
            ['state_id' => 14, 'name' => 'Urdaneta', 'code' => 'MIR020'],
            ['state_id' => 14, 'name' => 'Zamora', 'code' => 'MIR021'],

            // Monagas
            ['state_id' => 15, 'name' => 'Acosta', 'code' => 'MON001'],
            ['state_id' => 15, 'name' => 'Aguasay', 'code' => 'MON002'],
            ['state_id' => 15, 'name' => 'Bolívar', 'code' => 'MON003'],
            ['state_id' => 15, 'name' => 'Caripe', 'code' => 'MON004'],
            ['state_id' => 15, 'name' => 'Cedeño', 'code' => 'MON005'],
            ['state_id' => 15, 'name' => 'Ezequiel Zamora', 'code' => 'MON006'],
            ['state_id' => 15, 'name' => 'Libertador', 'code' => 'MON007'],
            ['state_id' => 15, 'name' => 'Maturín', 'code' => 'MON008'],
            ['state_id' => 15, 'name' => 'Piar', 'code' => 'MON009'],
            ['state_id' => 15, 'name' => 'Punceres', 'code' => 'MON010'],
            ['state_id' => 15, 'name' => 'Santa Bárbara', 'code' => 'MON011'],
            ['state_id' => 15, 'name' => 'Sotillo', 'code' => 'MON012'],
            ['state_id' => 15, 'name' => 'Uracoa', 'code' => 'MON013'],

            // Nueva Esparta
            ['state_id' => 16, 'name' => 'Antolín del Campo', 'code' => 'NES001'],
            ['state_id' => 16, 'name' => 'Arismendi', 'code' => 'NES002'],
            ['state_id' => 16, 'name' => 'Díaz', 'code' => 'NES003'],
            ['state_id' => 16, 'name' => 'García', 'code' => 'NES004'],
            ['state_id' => 16, 'name' => 'Gómez', 'code' => 'NES005'],
            ['state_id' => 16, 'name' => 'Maneiro', 'code' => 'NES006'],
            ['state_id' => 16, 'name' => 'Marcano', 'code' => 'NES007'],
            ['state_id' => 16, 'name' => 'Mariño', 'code' => 'NES008'],
            ['state_id' => 16, 'name' => 'Península de Macanao', 'code' => 'NES009'],
            ['state_id' => 16, 'name' => 'Tubores', 'code' => 'NES010'],
            ['state_id' => 16, 'name' => 'Villalba', 'code' => 'NES011'],

            // Portuguesa
            ['state_id' => 17, 'name' => 'Araure', 'code' => 'POR001'],
            ['state_id' => 17, 'name' => 'Agua Blanca', 'code' => 'POR002'],
            ['state_id' => 17, 'name' => 'Esteller', 'code' => 'POR003'],
            ['state_id' => 17, 'name' => 'Guanare', 'code' => 'POR004'],
            ['state_id' => 17, 'name' => 'Guanarito', 'code' => 'POR005'],
            ['state_id' => 17, 'name' => 'Monseñor José Vicente de Unda', 'code' => 'POR006'],
            ['state_id' => 17, 'name' => 'Ospino', 'code' => 'POR007'],
            ['state_id' => 17, 'name' => 'Páez', 'code' => 'POR008'],
            ['state_id' => 17, 'name' => 'Papelón', 'code' => 'POR009'],
            ['state_id' => 17, 'name' => 'San Genaro de Boconoíto', 'code' => 'POR010'],
            ['state_id' => 17, 'name' => 'San Rafael de Onoto', 'code' => 'POR011'],
            ['state_id' => 17, 'name' => 'Santa Rosalía', 'code' => 'POR012'],
            ['state_id' => 17, 'name' => 'Sucre', 'code' => 'POR013'],
            ['state_id' => 17, 'name' => 'Turén', 'code' => 'POR014'],

            // Sucre
            ['state_id' => 18, 'name' => 'Andrés Eloy Blanco', 'code' => 'SUC001'],
            ['state_id' => 18, 'name' => 'Andrés Mata', 'code' => 'SUC002'],
            ['state_id' => 18, 'name' => 'Arismendi', 'code' => 'SUC003'],
            ['state_id' => 18, 'name' => 'Benítez', 'code' => 'SUC004'],
            ['state_id' => 18, 'name' => 'Bermúdez', 'code' => 'SUC005'],
            ['state_id' => 18, 'name' => 'Bolívar', 'code' => 'SUC006'],
            ['state_id' => 18, 'name' => 'Cajigal', 'code' => 'SUC007'],
            ['state_id' => 18, 'name' => 'Cruz Salmerón Acosta', 'code' => 'SUC008'],
            ['state_id' => 18, 'name' => 'Libertador', 'code' => 'SUC009'],
            ['state_id' => 18, 'name' => 'Mariño', 'code' => 'SUC010'],
            ['state_id' => 18, 'name' => 'Mejía', 'code' => 'SUC011'],
            ['state_id' => 18, 'name' => 'Montes', 'code' => 'SUC012'],
            ['state_id' => 18, 'name' => 'Ribero', 'code' => 'SUC013'],
            ['state_id' => 18, 'name' => 'Sucre', 'code' => 'SUC014'],
            ['state_id' => 18, 'name' => 'Valdez', 'code' => 'SUC015'],

            // Táchira
            ['state_id' => 19, 'name' => 'Andrés Bello', 'code' => 'TAC001'],
            ['state_id' => 19, 'name' => 'Antonio Rómulo Costa', 'code' => 'TAC002'],
            ['state_id' => 19, 'name' => 'Ayacucho', 'code' => 'TAC003'],
            ['state_id' => 19, 'name' => 'Bolívar', 'code' => 'TAC004'],
            ['state_id' => 19, 'name' => 'Cárdenas', 'code' => 'TAC005'],
            ['state_id' => 19, 'name' => 'Córdoba', 'code' => 'TAC006'],
            ['state_id' => 19, 'name' => 'Fernández Feo', 'code' => 'TAC007'],
            ['state_id' => 19, 'name' => 'Francisco de Miranda', 'code' => 'TAC008'],
            ['state_id' => 19, 'name' => 'García de Hevia', 'code' => 'TAC009'],
            ['state_id' => 19, 'name' => 'Guásimos', 'code' => 'TAC010'],
            ['state_id' => 19, 'name' => 'Independencia', 'code' => 'TAC011'],
            ['state_id' => 19, 'name' => 'Jáuregui', 'code' => 'TAC012'],
            ['state_id' => 19, 'name' => 'José María Vargas', 'code' => 'TAC013'],
            ['state_id' => 19, 'name' => 'Junín', 'code' => 'TAC014'],
            ['state_id' => 19, 'name' => 'Libertad', 'code' => 'TAC015'],
            ['state_id' => 19, 'name' => 'Libertador', 'code' => 'TAC016'],
            ['state_id' => 19, 'name' => 'Lobatera', 'code' => 'TAC017'],
            ['state_id' => 19, 'name' => 'Michelena', 'code' => 'TAC018'],
            ['state_id' => 19, 'name' => 'Panamericano', 'code' => 'TAC019'],
            ['state_id' => 19, 'name' => 'Pedro María Ureña', 'code' => 'TAC020'],
            ['state_id' => 19, 'name' => 'Rafael Urdaneta', 'code' => 'TAC021'],
            ['state_id' => 19, 'name' => 'Samuel Darío Maldonado', 'code' => 'TAC022'],
            ['state_id' => 19, 'name' => 'San Cristóbal', 'code' => 'TAC023'],
            ['state_id' => 19, 'name' => 'San Judas Tadeo', 'code' => 'TAC024'],
            ['state_id' => 19, 'name' => 'Seboruco', 'code' => 'TAC025'],
            ['state_id' => 19, 'name' => 'Simón Rodríguez', 'code' => 'TAC026'],
            ['state_id' => 19, 'name' => 'Sucre', 'code' => 'TAC027'],
            ['state_id' => 19, 'name' => 'Torbes', 'code' => 'TAC028'],
            ['state_id' => 19, 'name' => 'Uribante', 'code' => 'TAC029'],
            ['state_id' => 19, 'name' => 'Ureña', 'code' => 'TAC030'],

            // Trujillo
            ['state_id' => 20, 'name' => 'Andrés Bello', 'code' => 'TRU001'],
            ['state_id' => 20, 'name' => 'Boconó', 'code' => 'TRU002'],
            ['state_id' => 20, 'name' => 'Bolívar', 'code' => 'TRU003'],
            ['state_id' => 20, 'name' => 'Candelaria', 'code' => 'TRU004'],
            ['state_id' => 20, 'name' => 'Carache', 'code' => 'TRU005'],
            ['state_id' => 20, 'name' => 'Escuque', 'code' => 'TRU006'],
            ['state_id' => 20, 'name' => 'José Felipe Márquez Cañizalez', 'code' => 'TRU007'],
            ['state_id' => 20, 'name' => 'Juan Vicente Campos Elías', 'code' => 'TRU008'],
            ['state_id' => 20, 'name' => 'La Ceiba', 'code' => 'TRU009'],
            ['state_id' => 20, 'name' => 'Miranda', 'code' => 'TRU010'],
            ['state_id' => 20, 'name' => 'Monte Carmelo', 'code' => 'TRU011'],
            ['state_id' => 20, 'name' => 'Motatán', 'code' => 'TRU012'],
            ['state_id' => 20, 'name' => 'Pampán', 'code' => 'TRU013'],
            ['state_id' => 20, 'name' => 'Pampanito', 'code' => 'TRU014'],
            ['state_id' => 20, 'name' => 'Rafael Rangel', 'code' => 'TRU015'],
            ['state_id' => 20, 'name' => 'San Rafael de Carvajal', 'code' => 'TRU016'],
            ['state_id' => 20, 'name' => 'Sucre', 'code' => 'TRU017'],
            ['state_id' => 20, 'name' => 'Trujillo', 'code' => 'TRU018'],
            ['state_id' => 20, 'name' => 'Urdaneta', 'code' => 'TRU019'],
            ['state_id' => 20, 'name' => 'Valera', 'code' => 'TRU020'],

            // La Guaira
            ['state_id' => 21, 'name' => 'Vargas', 'code' => 'VAR001'],

            // Yaracuy
            ['state_id' => 22, 'name' => 'Arístides Bastidas', 'code' => 'YAR001'],
            ['state_id' => 22, 'name' => 'Bolívar', 'code' => 'YAR002'],
            ['state_id' => 22, 'name' => 'Bruzual', 'code' => 'YAR003'],
            ['state_id' => 22, 'name' => 'Cocorote', 'code' => 'YAR004'],
            ['state_id' => 22, 'name' => 'Independencia', 'code' => 'YAR005'],
            ['state_id' => 22, 'name' => 'José Antonio Páez', 'code' => 'YAR006'],
            ['state_id' => 22, 'name' => 'La Trinidad', 'code' => 'YAR007'],
            ['state_id' => 22, 'name' => 'Manuel Monge', 'code' => 'YAR008'],
            ['state_id' => 22, 'name' => 'Nirgua', 'code' => 'YAR009'],
            ['state_id' => 22, 'name' => 'Peña', 'code' => 'YAR010'],
            ['state_id' => 22, 'name' => 'San Felipe', 'code' => 'YAR011'],
            ['state_id' => 22, 'name' => 'Sucre', 'code' => 'YAR012'],
            ['state_id' => 22, 'name' => 'Urachiche', 'code' => 'YAR013'],
            ['state_id' => 22, 'name' => 'Veroes', 'code' => 'YAR014'],

            // Zulia
            ['state_id' => 23, 'name' => 'Almirante Padilla', 'code' => 'ZUL001'],
            ['state_id' => 23, 'name' => 'Baralt', 'code' => 'ZUL002'],
            ['state_id' => 23, 'name' => 'Cabimas', 'code' => 'ZUL003'],
            ['state_id' => 23, 'name' => 'Catatumbo', 'code' => 'ZUL004'],
            ['state_id' => 23, 'name' => 'Colón', 'code' => 'ZUL005'],
            ['state_id' => 23, 'name' => 'Francisco Javier Pulgar', 'code' => 'ZUL006'],
            ['state_id' => 23, 'name' => 'Jesús Enrique Lossada', 'code' => 'ZUL007'],
            ['state_id' => 23, 'name' => 'Jesús María Semprún', 'code' => 'ZUL008'],
            ['state_id' => 23, 'name' => 'La Cañada de Urdaneta', 'code' => 'ZUL009'],
            ['state_id' => 23, 'name' => 'Lagunillas', 'code' => 'ZUL010'],
            ['state_id' => 23, 'name' => 'Machiques de Perijá', 'code' => 'ZUL011'],
            ['state_id' => 23, 'name' => 'Mara', 'code' => 'ZUL012'],
            ['state_id' => 23, 'name' => 'Maracaibo', 'code' => 'ZUL013'],
            ['state_id' => 23, 'name' => 'Miranda', 'code' => 'ZUL014'],
            ['state_id' => 23, 'name' => 'Guajira', 'code' => 'ZUL015'],
            ['state_id' => 23, 'name' => 'Rosario de Perijá', 'code' => 'ZUL016'],
            ['state_id' => 23, 'name' => 'San Francisco', 'code' => 'ZUL017'],
            ['state_id' => 23, 'name' => 'Santa Rita', 'code' => 'ZUL018'],
            ['state_id' => 23, 'name' => 'Simón Bolívar', 'code' => 'ZUL019'],
            ['state_id' => 23, 'name' => 'Sucre', 'code' => 'ZUL020'],
            ['state_id' => 23, 'name' => 'Valmore Rodríguez', 'code' => 'ZUL021'],

            // Distrito Capital
            ['state_id' => 24, 'name' => 'Libertador', 'code' => 'DC001'],
        ];

        DB::table('municipalities')->insert($municipalities);
    }
}